name: ScoreHud
main: JackMD\ScoreHud\ScoreHud
api: [3.0.0]
version: 9.9.9
author: Jack-loser
description: Add fully customizable scoreboards to your server.

virions:
- ScoreFactory
- UpdateNotifier
- ConfigUpdater

permissions:
  sh.command.sh:
    default: true
    description: Fuck
